### ISSUE TITLE
Issues in 8.1

### ISSUE THREAD

**Issue by bavedradley** [notoriousbdg/vrops-dashboard-vm_base_cost_analysis#1]
First question, does this work in version 8.1?

if not, then you can ignore this...

I installed the dashboard and in the Cluster Cost summary (demand based) I just get an Internal Server error displayed.

**Comment by notoriousbdg** [comment]
This dashboard is no longer needed for 8.1 because it's been added as a native dashboard.  You can find it at Cost/Base Rate Analysis.
